name: gps
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.6.0=h6a678d5_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.7.15=h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - curl=8.12.1=h251f7ec_0
  - dav1d=1.2.1=h5eee18b_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=h2a67f75_3
  - fontconfig=2.14.1=h55d465d_3
  - freetype=2.13.3=h4a9f257_0
  - gettext=0.21.0=hedfda30_2
  - giflib=5.2.2=h5eee18b_0
  - git=2.45.2=pl5402h72990fb_2
  - graphite2=1.3.14=h295c915_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - icu=73.1=h6a678d5_0
  - jpeg=9e=h5eee18b_3
  - krb5=1.20.1=h143b758_1
  - lame=3.100=h7b6447c_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libarchive=3.7.7=hfab0078_0
  - libcurl=8.12.1=hc9e6f67_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libglib=2.84.2=h37c7471_0
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpng=1.6.39=h5eee18b_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.1.1=h7f8727e_3
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxml2=2.13.8=hfdd30dd_0
  - lz4-c=1.9.4=h6a678d5_1
  - ncurses=6.4=h6a678d5_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=h0d4d230_1
  - openssl=3.0.17=h5eee18b_0
  - pcre2=10.42=hebb0a14_1
  - perl=5.40.2=0_h5eee18b_perl5
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=hb25bd0a_2
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.11.13=h1a3bd86_0
  - readline=8.2=h5eee18b_0
  - setuptools=78.1.1=py311h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tesseract=5.2.0=h6a678d5_2
  - tk=8.6.14=h993c535_1
  - wheel=0.45.1=py311h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=hd233ad5_2
  - zstd=1.5.6=hc292b87_0
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bokeh==3.1.1
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cmasher==1.9.2
      - colorspacious==1.1.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - executing==2.2.0
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - jax==0.4.33
      - jaxlib==0.4.33
      - jedi==0.19.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lightning==2.3.3
      - lightning-utilities==0.11.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - ml-dtypes==0.5.3
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - narwhals==1.41.0
      - networkx==3.1
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plotly==6.1.2
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - propcache==0.2.0
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.4.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2024.3.5
      - requests==2.32.3
      - rich==14.0.0
      - rootutils==1.0.7
      - scipy==1.16.3
      - seaborn==0.13.2
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - stack-data==0.6.3
      - sympy==1.13.3
      - torch==2.4.1
      - torchfsm==0.0.5
      - torchmetrics==1.5.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - vape4d==0.2.7
      - wandb==0.19.11
      - wcwidth==0.2.13
      - xyzservices==2025.4.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/pfister/anaconda3/envs/gps
