name: gps
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.7.15
  - cairo=1.16.0
  - curl=8.12.1
  - dav1d=1.2.1
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - freetype=2.13.3
  - gettext=0.21.0
  - giflib=5.2.2
  - git=2.45.2
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - jpeg=9e
  - krb5=1.20.1
  - lame=3.100
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libarchive=3.7.7
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libglib=2.84.2
  - libgomp=11.2.0
  - libiconv=1.16
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - ncurses=6.4
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.0.17
  - pcre2=10.42
  - perl=5.40.2
  - pip=25.1
  - pixman=0.40.0
  - pthread-stubs=0.3
  - python=3.11.13
  - readline=8.2
  - setuptools=78.1.1
  - sqlite=3.45.3
  - tesseract=5.2.0
  - tk=8.6.14
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxrender=0.9.12
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - bokeh==3.1.1
      - certifi==2025.4.26
      - cffi==1.17.1
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cmasher==1.9.2
      - colorspacious==1.1.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - executing==2.2.0
      - filelock==3.16.1
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - hydra-core==1.3.2
      - idna==3.10
      - imageio==2.35.1
      - imageio-ffmpeg==0.5.1
      - importlib-resources==6.4.5
      - ipython==9.4.0
      - ipython-pygments-lexers==1.1.1
      - jedi==0.19.2
      - jinja2==3.1.6
      - kiwisolver==1.4.7
      - lightning==2.3.3
      - lightning-utilities==0.11.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - moviepy==1.0.3
      - mpmath==1.3.0
      - multidict==6.1.0
      - narwhals==1.41.0
      - networkx==3.1
      - numpy==1.24.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.9.41
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - packaging==24.2
      - pandas==2.0.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - plotly==6.1.2
      - proglog==0.1.12
      - prompt-toolkit==3.0.51
      - propcache==0.2.0
      - protobuf==5.29.5
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pygments==2.19.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytorch-lightning==2.4.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2024.3.5
      - requests==2.32.3
      - rich==14.0.0
      - rootutils==1.0.7
      - seaborn==0.13.2
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - six==1.17.0
      - smmap==5.0.2
      - soundfile==0.13.1
      - stack-data==0.6.3
      - sympy==1.13.3
      - torch==2.4.1
      - torchfsm==0.0.5
      - torchmetrics==1.5.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==3.0.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - vape4d==0.2.7
      - wandb==0.19.11
      - wcwidth==0.2.13
      - xyzservices==2025.4.0
      - yarl==1.15.2
      - zipp==3.20.2
prefix: /home/pfister/miniconda3/envs/gps
