usetex: false
fontsize: 10
plot_formats: ["pdf"]

video:
  enabled: false
  fps: 3
  format: "mp4"
  warmup: 100
  num_frames: 30
  normalize: "global"

metrics:
  mse:
    enabled: false
    warmup_len: 100
    num_seqs: 10
    seq_len: 10

  mean_std:
    enabled: true
    warmup_len: 100
    num_samples: 1000
    delta: 1
    seeds: [42, 43, 44]
    cmap_mean: "icefire"
    cmap_std: "OrRd"
    diff: false
    show_overshoot: false
    overshoot_tresh: 0.0
    grid_cols: 3

  enstrophy:
    enabled: false
    num_seqs: 5
    seq_len: 10
    loglog: true
    incl_const: false

debug:
  denoising:
    enabled: false
    fps: 1
    normalize: "global"

  variance:
    enabled: false
    warmup_len: 100
    num_samples: 100
    fps: 10
    delta: 1
    seed: 42
    normalize: "global"

  std_steps:
    enabled: false
    steps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 100]
    warmup_len: 100
    num_samples: 1000
    delta: 1
    seed: 42

  mean_std_rel_err_steps:
    enabled: false
    steps: [1, 5, 10]
    warmup_len: 100
    num_samples: 100
    delta: 1
    seeds: [42, 43, 44, 45, 46]

  std_rel_err_grid:
    enabled: false
    steps: [1, 5, 10]
    g_coefs: [0.5, 1.0]
    warmup_len: 100
    num_samples: 100
    delta: 1
    seeds: [42, 43]

channel_titles: ["vort"]
