
_target_: models.diffusion_model.DiffusionModel
cfg:
  _target_: models.diffusion_model.DiffusionModelCfg
  # General model parameters
  dim: ${data.dim}
  ctx_len: ${data.ctx_len}
  sim_fields: ${data.sim_fields}
  sim_params: ${data.sim_params}

  # Diffusion-specific parameters
  timesteps: 100
  beta_schedule: "linear"
  cond_noising: true

  # Network configuration
  net:
    _target_: models.components.unet.Unet
    channels: ${mul:${data.num_channels},${add:${data.ctx_len},1}}
    out_dim: ${data.num_channels}
    dim: 128
    dim_mults: [1, 1, 1]
    use_convnext: true
    convnext_mult: 1

  # Optimization parameters
  lr: 1e-4
  weight_decay: 0.0

  # Evaluation
  num_steps_eval: 100

  # Logging configuration
  eval_config: ${evaluation}
